/**
 * Writes supabase/seed.sql from the sample catalogue in src/data/mockProducts.ts,
 * so the database starts with exactly the products the site shows today.
 *
 *   npm run db:seed      (then paste supabase/seed.sql into the Supabase SQL Editor)
 *
 * Re-running the seed updates existing rows instead of duplicating them.
 */
import { writeFileSync } from 'node:fs'
import { mockBrands, mockCategories, mockProductTypes, mockProducts } from '../src/data/mockProducts.ts'

const q = (v: unknown): string => {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'number') return String(v)
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  return `'${String(v).replace(/'/g, "''")}'`
}

const upsert = (table: string, cols: string[], rows: unknown[][]) =>
  `insert into public.${table} (${cols.join(', ')}) values\n` +
  rows.map((r) => `  (${r.map(q).join(', ')})`).join(',\n') +
  `\non conflict (id) do update set ${cols.filter((c) => c !== 'id').map((c) => `${c} = excluded.${c}`).join(', ')};\n`

const sql = [
  '-- Generated by scripts/generate-seed.ts — do not edit by hand.',
  '-- Sample catalogue for Fit Heiress NG. Run AFTER migrations/0001_schema.sql.',
  '',
  upsert('categories', ['id', 'name', 'description', 'sort_order'], mockCategories.map((c, i) => [c.id, c.name, c.description, i])),
  upsert('product_types', ['id', 'name', 'category_id', 'sort_order'], mockProductTypes.map((t, i) => [t.id, t.name, t.categoryId, i])),
  upsert('brands', ['id', 'name', 'tagline', 'sort_order'], mockBrands.map((b, i) => [b.id, b.name, b.tagline, i])),
  upsert(
    'products',
    ['id', 'slug', 'name', 'short_description', 'description', 'price', 'discount_percent', 'image', 'category_id', 'brand_id', 'type_id',
      'stock_quantity', 'rating', 'rating_count', 'featured', 'specs', 'sort_order'],
    mockProducts.map((p, i) => [p.id, p.slug, p.name, p.shortDescription, p.description, p.price, p.discountPercent ?? null, p.image,
      p.categoryId, p.brandId, p.typeId, p.stockQuantity, p.rating ?? null, p.ratingCount ?? null, !!p.featured, JSON.stringify(p.specs ?? []), i]),
  ).replace(/'(\[\{.*?\}\]|\[\])'/g, "'$1'::jsonb"),
].join('\n')

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql)
console.log(`Wrote supabase/seed.sql: ${mockCategories.length} categories, ${mockProductTypes.length} types, ${mockBrands.length} brands, ${mockProducts.length} products`)
